### ISSUE TITLE
rate for metric

### ISSUE THREAD

**Issue by ihard** [bzed/whisper-to-graphite#1]
may be set rate for send metric?
1 worker does it too fast :)

**Comment by bzed** [comment]
hmm, that sounds more like your backend is too slow. I was happily migrating data with ~20 workers at the same time.... but I'll happily accept patches :)

**Comment by bzed** [comment]
What are you using as backend? I recommend carbon-clickhouse and clickhouse!

**Comment by ihard** [comment]
backend now carbon-clickhouse and clickhouse :) migrate from go-carbon

**Comment by bzed** [comment]
Please give the current version a try - rate limit was added with 698d5d500282761993ce1c7d16773ac686ca21aa
