### ISSUE TITLE
The program produces points for every archive automatically

### ISSUE THREAD

**Issue by Felixoid** [bzed/whisper-to-graphite#7]
Hello. Here's the reference file for an issue
[counter.wsp.gz](https://github.com/bzed/whisper-to-graphite/files/4183097/counter.wsp.gz)

When you are trying to dump it with command `./whisper-to-graphite -basedirectory . -directory . -from 1581019200 -to 1581022800 -host localhost -port 42003 -workers 1`, it produces the next data 
[dump.txt](https://github.com/bzed/whisper-to-graphite/files/4183107/dump.txt)

There are 3 1581019200 and 1581022800 timestamps with aggregated values. I'm not entirely sure how is it possible, but because of that, the graph looks quite scary. 
![Screenshot_2020-02-10 New dashboard - Grafana](https://user-images.githubusercontent.com/3025537/74191794-84f78800-4c54-11ea-8068-a6f88048258d.png)
The data from 21:00 to 14:00 was reuploaded.

For me, it looks like the whisper dumps not only existing data but as well it applies the aggregation for some reason.

Maybe, you have a quick idea of how to fix it?

**Comment by bzed** [comment]
You could use ```whisper-dump``` to investigate:

```
% whisper-dump counter.wsp | grep -e 'Archive' -e 1581019200 -e 1581022800
Archive 0 info:
Archive 1 info:
Archive 2 info:
Archive 0 data:
4817: 1581019200, 210389053437
4877: 1581022800, 210583595343
Archive 1 data:
3267: 1581019200, 210395104485.600006103515625
3279: 1581022800, 210591876450
Archive 2 data:
2432: 1581019200, 210482458763.200042724609375
2433: 1581022800, 210685749661.283355712890625
```

Your whisper file has 3 archives with the mentioned datapoints. Maybe an uncommon/bad storage schema? Or did you have a config in ```storage-aggregation.conf```? Could be the min/avg/max aggregation?

I fear you'll have to figure this out, so far there is no way to filter things from the archives, patches are welcome :)

**Comment by Felixoid** [comment]
I've found a problem place: https://github.com/bzed/go-whisper/blob/master/whisper.go#L415

It dumps just all data, despite the crossing of archives. It looks like for fix it should be the different analog of whisper.Fetch or whisper.DumpArchives, which would return the data, but will respect crossings and drop data from older archives.

**upd** answered without reading ^_^

So, the crossing data isn't a normal case for whisper files?

**Comment by Felixoid** [comment]
There's my aggregation and storage schema

```
# aggregation
[default_average]
pattern = .*
xFilesFactor = 0.5
aggregationMethod = average

[default]
pattern = ^.*
retentions = 60s:14d,5m:45d,1h:2y
```

We are using https://github.com/grobian/carbonwriter as carbon writers, which uses the fork from the same go-whisper project, as far as I see

**Comment by Felixoid** [comment]
Hey @bzed 

I've done another experiment with a usage of only default whisper tools

```
$ whisper-create.py here.wsp 60s:14d 5m:45d 1h:2y
Created: here.wsp (607732 bytes)
$ ls here.wsp counter.wsp -l
-rw-r--r-- 1 mikhail.shiryaev mikhail.shiryaev 607732 Feb 10 20:34 counter.wsp
-rw-r--r-- 1 mikhail.shiryaev mikhail.shiryaev 607732 Feb 11 12:12 here.wsp
$ start=$(date +%s -d '1 day ago'); end=$(date +%s )
$ echo {$start..$end..60}
{1581336804..1581423204..60}
$ whisper-update.py here.wsp {1581336804..1581423204..60}:$((RANDOM % 180))
```

The resulting file is 
[here.wsp.gz](https://github.com/bzed/whisper-to-graphite/files/4185608/here.wsp.gz), it contains the data in every of 3 archives. Looks like whisper-to-graphite should use different to whisper.DumpArchives logic. Like to dump archives one by one, but drop points which are newer than the oldest existing

**Comment by Felixoid** [comment]
@bzed what would you say regarding a change in DumpArchives function? Would it be better to create another method to get only older points from each next archive or tweak the current one? I couldn't imagine that somebody wants to have not unique values from whisper file, but who knows..
